# Generated by Django 5.2.8 on 2025-11-09 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Préférences'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['-created_at'], name='chat_app_ch_created_c46239_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-created_at'], name='chat_app_ch_user_id_b8d55d_idx'),
        ),
    ]
