# Generated by Django 5.2.8 on 2025-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_userprofile_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='sources_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Sources JSON'),
        ),
    ]
